name: Tabris Build
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    # Job name
    name: Foo
    steps:
    - uses: actions/checkout@v1
    - run: echo "Hello Tabris.js!"