name: Tabris Build
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    # Job name
    name: Foo
    steps:
    - uses: actions/checkout@v1
    - run: echo "Hello Tabris.js!"
    - name: Where am I?
      run: pwd && ls -la
    - name: How is Docker?
      run: docker --version && docker ps
    - name: Build the Tabris Docker image
      run: docker build . --file Dockerfile --tag tabris-js-build-android:2.x